### ISSUE TITLE
Javascript Placeholders Not Working

### ISSUE THREAD

**Issue by MidnightSugar** [PlaceholderAPI/Javascript-Expansion#10]
[Request change (Wiki)]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=change_request_wiki.md
[Request change (PlaceholderAPI)]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues/new?template=change_request_placeholderapi.md
[Spigot]: https://www.spigotmc.org/resources/6245/
[Jenkins]: http://ci.extendedclip.com/job/PlaceholderAPI/
[issues]: https://github.com/PlaceholderAPI/PlaceholderAPI/issues

## Please read
This template is only for reporting bugs of PlaceholderAPI!  
If you want to request changes to the code of PlaceholderAPI, use the [Request change (PlaceholderAPI)] template.  
For changes to the wiki use the [Request change (Wiki)] template.

Please also make sure that you use the [latest release][Spigot] or the latest [developement build][Jenkins] and that your bug isn't already reported on the [issues] page.

**Please report issues with expansions/placeholders to the corresponding issue tracker! Only report it here if you can't find any place to report it!**

### Issue
> What is the issue? Describe it like you would tell a friend.

Javascript placeholders broken in from paper version 61 onwards. version 60 is the last paper build that the scripts successfully load.

[06:37:41] [Server thread/WARN]: [PlaceholderAPI] Failed to set ScriptEngine for javascript placeholder: town
[06:37:41] [Server thread/WARN]: [PlaceholderAPI] Failed to set ScriptEngine for javascript placeholder: nation
[06:37:41] [Server thread/WARN]: [PlaceholderAPI] Failed to set ScriptEngine for javascript placeholder: invite
[06:37:41] [Server thread/WARN]: [PlaceholderAPI] Failed to set ScriptEngine for javascript placeholder: prefix
[06:37:41] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: javascript

### Expected behaviour
> What should PlaceholderAPI do?

Javascript placeholders should load

### Actual behaviour
> What does PlaceholderAPI actually do?

The placeholders don't load.

### How to reproduce
> What steps did you made, to get this bug?

1. Create javascript placeholder
2. Go on paper build 61 onwards

**Comment by aBooDyy** [comment]
I remember someone has brought this up on discord recently, and he fixed it by using an older paper build (can't remember which one).
You can try doing the same as for now until it gets fixed.

**Comment by MidnightSugar** [comment]
That was me lol. But I can't do that unfortunately since I went to 1.15.2. And I can't go back to 1.15.1.

**Comment by MidnightSugar** [comment]
I am using java 8 right now. Could updating my java version fix this?

**Comment by ysy960108** [comment]
Hello, I got the same issue here, and I found the plugin MythicMobsExtension cause the problem, which supports javascript as well. 
The Javascript on PAPI works well as I turned JS support off in MythicMobsExtension's config.
Hope this helps.

**Comment by MidnightSugar** [comment]
Thanks, I don't have mythicmobsextension, so there must be another plugin causing problems. Weird that it was working before.

**Comment by PolarAvatar** [comment]
I had the same problem but i solved it by switching to java 11

**Comment by EnTIv** [comment]
Chatcontrol 9.0.4 will causes the same problem

**Comment by BlackBeltPanda** [comment]
I'm also having this issue in 1.15.2. I don't have MythicMobsExtension but I do have ChatControl Pro 8.7.3.

**Comment by Andre601** [comment]
I personally believe this is probably caused by how ChatControl Pro handles the placeholders and less by PlaceholderAPI or this Expansion itself.

If it works without CCP then that plugin is clearly the cause of the issue and you should nag the dev about it. He can always join the HelpChat Discord for some help. https://discord.gg/helpchat
