### ISSUE TITLE
Issue in switch comparison

### ISSUE THREAD

**Issue by BBSnowIce** [PlaceholderAPI/Javascript-Expansion#18]
When I try to make a switch (or an if, else if, else comparison), sometimes the switch does not match the argument and I get an other output.

I noticed this issue with this script too https://raw.githubusercontent.com/PlaceholderAPI/Javascript-Expansion/master/scripts/data_example.js. The getUsage function seems to not be able to sort action as expected sometimes. It's a bit anoying because some times the placeholder will remove instead of add values... We can see this more visually on scoreboard plugins or holograms plugins.

**Comment by LegalSmeagol** [comment]
Also receive this issue. It seems like upon a server restart, the output values from an if, else if, else statement are inconsistent and unrelated to the specified output. For example I have a script that I've told to output the number of Towny residents, and this instead outputs the Towny town name - using /jsexpansion reload will usually fix this after around 5-6 tries - but if reloaded again or server restart, the placeholder will once again output the wrong value.

**Comment by thienbao860** [comment]
Hi. I have been noticing this issue for a while now. I will try to keep it updated to 1.6.1 for bug fixture. Thanks for reporting
