### ISSUE TITLE
Javascript placeholders stop working when ChatControl is active.

### ISSUE THREAD

**Issue by itaquito** [PlaceholderAPI/Javascript-Expansion#22]
Hello!

I made some Javascript placeholder in order to make some very specific tasks on my server, all of them worked fine, no errors on the console when I use them or nothing that meant that they aren't working properly.
The issue started happening just when I install ChatControl, now the placeholders aren't loading and this error appears on the console every time the server starts and also when I reload PAPI.
https://pastebin.com/ebxDaiup

If I uninstall ChatControl, the placeholders work back again. I already opened this same issue on ChatControl and I'm waiting for there response. 
Extra note: All that placeholders that don't have to do with Javascript work fine.

PAPI version:
`[16:22:09 INFO]: PlaceholderAPI version 2.10.6`
Paper spigot version:
`[16:22:29 INFO]: This server is running Paper version git-Paper-334 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)`

Thanks

**Comment by darbyjack** [comment]
Related to #21 21

**Comment by itaquito** [comment]
Oh, it is a duplicate issue of #21 
I didn't see that, hehe thanks anyways.
