### ISSUE TITLE
A way to parse PAPI placeholders through multiples strings ?

### ISSUE THREAD

**Issue by Tanguygab** [PlaceholderAPI/Javascript-Expansion#23]
Hey, I wanted to know if there was a way to parse a placeholder through multiples strings, so it would let me use variables inside of that placeholder.
Here's what I have:
```js
function test() {
	return '%' + 'listplayers_with_perm_' +args[0] + '%'

}
test()
```
If I do that, I will get the placeholder unparsed =/

Is there a way to parse it or could you add one ? thanks =)

**Comment by Tanguygab** [comment]
Welp, Frosty told me how to do that on discord,
> @Tanguygab you can get the papi instance
And parse it using papi.parsePlaceholders(player, string);

**Comment by Andre601** [comment]
Yep. The method is static so `PlaceholderAPI.parsePlaceholders(String, Player)` would work too.
