### ISSUE TITLE
Script for Community Scripts

### ISSUE THREAD

**Issue by Tanguygab** [PlaceholderAPI/Javascript-Expansion#24]
Hey 👋 
I wanted to share my ListPlayers script to the community, and BlitzZ and cj recommended me to post it here, so here it is =)
[listplayers.txt](https://github.com/PlaceholderAPI/Javascript-Expansion/files/4847006/listplayers.txt)
Also, I don't know if you really want to add it, but in case, here's a [OneDrive link](https://1drv.ms/u/s!Avo6knYMxCGfhu5TAeYxNRP3H22Ghg) to the file because I'm planning on updating it later. If you don't want to add it then ok, I'll just reopen an issue when I think it's good to be updated =)
(Yes, I know, it's a .txt file, blame GitHub for not allowing .js files)

**Comment by Tanguygab** [comment]
Forgot to mention, %javascript_listplayers% can be directly parsed to show the syntax

**Comment by cj89898** [comment]
What are the placeholders?

**Comment by Tanguygab** [comment]
Quick update https://paste.helpch.at/ejawafegaf.js
- For the nearby list type, you can now use `no` as 4th argument to not count you in the list.
- Added help usage for nearby list type.
- And fixed the `Offline` msg where I left a thing from my experiences x)
