### ISSUE TITLE
Update for the ListPlayers script

### ISSUE THREAD

**Issue by Tanguygab** [PlaceholderAPI/Javascript-Expansion#25]
Here's the update: https://paste.helpch.at/gibemikeyo.js

New:
 - [+] Offline players list
 - [+] All (Online+Offline) players list
 - [-] Removed PAPI placeholders support with [] atm, {} still works tho
 - [~] Rework of the syntax:
`%javascript_listplayers_<type>,<subtype>,<yes/no>,<output>,<subtype value>%`

Types: `online, offline, all`
SubTypes: `normal, perm, world, nearby`
Outputs: `list, amount, a number`
SubType values: `a permission, a world, a radius`

**Note:** `offline` and `all` types only support the `normal` subtype.

**Comment by iSkyify** [comment]
SICK!

**Comment by cj89898** [comment]
Updated

**Comment by Tanguygab** [comment]
Can you update it again ? =) https://paste.helpch.at/usezebobid.js
It adds back support for [placeholder]

**Comment by lensfort** [comment]
How do I apply this js to be able to fix my ListPlayers on my server?
