### ISSUE TITLE
Suggestion: Use utf-8 format for return string in js file

### ISSUE THREAD

**Issue by BingYanchi** [PlaceholderAPI/Javascript-Expansion#29]
When I tried to use Chinese in the return string, an encoding error occurred.

test.js
```
function main() {
	return "测试"
} main();
```
The output using /papi parse:
![image](https://user-images.githubusercontent.com/36477925/90984574-63367080-e5a8-11ea-856f-c36f1bd48c76.png)

Paper 1.16.1
PlaceholderAPI 2.10.9

**Comment by BomBardyGamer** [comment]
Can you show the stack trace please?

**Comment by BingYanchi** [comment]
> Can you show the stack trace please?

I don't know how to operate, and I haven't encountered such a situation. Maybe you can try the above method to reproduce this situation.

**Comment by thienbao860** [comment]
It's simply because you have no semicolon after the return part: 
`function main() {
	return "测试";
} 
main();`

**Comment by BingYanchi** [comment]
> It's simply because you have no semicolon after the return part:
> `function main() { return "测试"; } main();`

I tried it, but the phenomenon reappeared. This may not be the problem.

**Comment by BingYanchi** [comment]
> It's simply because you have no semicolon after the return part:
> `function main() { return "测试"; } main();`

Maybe there is something wrong with the encoding of the return output method, or it only appears in 1.16?
