### ISSUE TITLE
How to use Native Java API of Other Plugins inside JavaScript Pleaceholder?

### ISSUE THREAD

**Issue by anar4732** [PlaceholderAPI/Javascript-Expansion#30]
for exepmle. i need to use `me.chemmic.main.API.ChatColorAPI.getChatColorCode(Player)`

i know ChatColor have PAPI hook but i need to use it in a JS pleaceholder.

i tried to use `var chatColorAPIClass = Java.type('me.chemmic.main.API.ChatColorAPI');`
but thorws error "class not found" (but plugin installed)

**Comment by Jiale23** [comment]
Hey guys,how did you resolve it?I want to do it with the same method.
Thanks!
