### ISSUE TITLE
New Community Script: OnlinePlayerList

### ISSUE THREAD

**Issue by joex92** [PlaceholderAPI/Javascript-Expansion#37]
- **Author:** JoeX92
- **Description:** List the current Online Players
- **Usage:** `%javascript_onlinePlayerList_<delimiter>%` (Default delimiter: "`, `")
- **Example:** `%javascript_onlinePlayerList_|%` - Outputs: "player1|player2|player3"

**Javascript Code**

`onlinePlayerList.js`
```js
function onlinePlayerList() {
    var delimiter = ", ";
    if (args.length == 1 && args[0] != null) {
        delimiter = String(args[0]);
    }
    var onPlayersStr = "";
    var onPlayers = BukkitServer.getOnlinePlayers().toArray();
    for (i = 0;i < onPlayers.length; i++){
        var player = onPlayers[i];
        if (i == 0){
            onPlayersStr = player.getName();
        } else {
            onPlayersStr = onPlayersStr + delimiter + player.getName();
        }
    }
    return onPlayersStr;
}
onlinePlayerList();
```
**Add to** `javascript_placeholders.yml`
```yaml
onlinePlayerList:
  file: onlinePlayerList.js
```

**Comment by BlitzOffline** [comment]
Hello. So this is a cool placeholder but could you please explain why this placeholder should be used over the [PlayerList](https://api.extendedclip.com/expansions/playerlist/) expansion? We try to only add placeholders that don't exist in other expansions and in my opinion the PlayerList does this job and a lot more.

**Comment by joex92** [comment]
oh, the only one I knew was [ListPlayer](https://api.extendedclip.com/expansions/listplayers/) and when I tried to install it, it wasn't being "supported" `[Sun, 6. Jun 2021 17:50:06 UTC WARN] listplayers is attempting to register placeholders via a PlaceholderHook class which is no longer supported!`, So I thought that was the only one with what I wanted... I'm going to try [PlayerList](https://api.extendedclip.com/expansions/playerlist/) then, for some reason I didn't see it...

also, I want to use this placeholder as an Alert in DiscordSRV, but for some reason my script works in console, works in Minecraft chat, but it doesn't work sending it through an Alert... it's weird... hopefully PlayerList will work...

**Comment by joex92** [comment]
Now I remember why I didn't use [PlayerList](https://api.extendedclip.com/expansions/playerlist/)
![image](https://user-images.githubusercontent.com/645579/120935067-a2145d80-c6c6-11eb-893d-7bffe051f3b5.png)

**Comment by BlitzOffline** [comment]
Well that's strange bcz for me it works:
![image](https://user-images.githubusercontent.com/52609756/120935330-e9244200-c70a-11eb-8dff-6dc41df2b4a9.png)

U could try to just manually download it.

Download it from here: <https://api.extendedclip.com/expansions/playerlist/>
and put it in `plugins/PlaceholderAPI/expansions` and then do `/papi reload`

**Comment by joex92** [comment]
thanks! it worked! the host I'm using is constantly sending `/list` to the console, so I wanted to take advantage of that to get the list of players and send it to the console chat in Discord, here's the alert if anyone looks for it:
```yaml
  - Trigger: ServerCommandEvent
    Channel: console
    Conditions:
      - '#event.getCommand().equals("list")'
    Embed:
      Color: "#00ff00"
      Author:
        Name: 'Online players: ${#server.onlinePlayers.size()}'
      Description: "%playerlist_online,normal,yes,list%"
```
this is the output:
![image](https://user-images.githubusercontent.com/645579/120937965-26221180-c6d6-11eb-98e0-b2fd2f27d06e.png)

**Comment by joex92** [comment]
but I tested out, and the list of players is sent as 1 string separated by "`, `"... and I wanted to separate them by "`\n`" so it shows one above the other...

**Comment by BlitzOffline** [comment]
Well you can always use the javascript for that but yeah the reason we won't put this on the wiki is bcz there's already a better alternative I guess

**Comment by joex92** [comment]
🤔  hmm... you are right! I'm going to use javascript to replace "`, `" with "`\n`"...
anyways, thanks!
