### ISSUE TITLE
Parameter separator

### ISSUE THREAD

**Issue by 157946a** [PlaceholderAPI/Javascript-Expansion#40]
Cannot use custom separators, only the default comma separator, what is the problem, environment: paper-1.12.2, java8, JavaScript extension 1.6.0, papi2.10.9

**Comment by iGabyTM** [comment]
If you can't use java 16, I guess you can ask someone to edit the old expansion code for you.

**Comment by BlitzOffline** [comment]
> Extensions require java16, but I don’t need to use 16 at the moment, or 16 has no js function, I don’t really want to use it, and I don’t know if some plugins support 16

It requires java 15+ and if you really can't or don't want to update, you can do what gaby said. We do not support old versions anymore. The reason updates are made is to fix bugs and improve stuff. If you're willing to stay on java 8 then I'm afraid you'll have to also stay with that bug.

Also I am almost certain that on version 1.6.0 separators used to work. Only separator that doesn't work is one underscore.

Going to close this now.
