### ISSUE TITLE
Scripts not working on 1.17 / Java 16

### ISSUE THREAD

**Issue by CroaBeast** [PlaceholderAPI/Javascript-Expansion#41]
I recently upgrade my server to 1.17 and Java 16.
In PAPI Discord they told me to use the last version in the `#1_17` channel, but even so, my scripts are not working.

Error: [Click here](https://paste.helpch.at/uboqonomev.shell)
The script: [Click here](https://paste.helpch.at/eyixoyalar.cs)

**Comment by Funny-cube** [comment]
Please report issues for that particular dev build on the relevant pull request,
https://github.com/PlaceholderAPI/Javascript-Expansion/pull/36

Thanks!
