### ISSUE TITLE
Unable to load

### ISSUE THREAD

**Issue by Zz-886** [PlaceholderAPI/Javascript-Expansion#47]
![image](https://user-images.githubusercontent.com/55978588/129826636-ab13d29e-4cac-4639-b5ce-b1c1f76fe24b.png)

**Comment by Andre601** [comment]
Update your Java version, you're using an unsupported version

**Comment by Baterka** [comment]
So I need to use Java 16 even for 1.16 server?

**Comment by Andre601** [comment]
That or an older version of the expansion I would assume
