### ISSUE TITLE
Javascript Extension Files not loading.

### ISSUE THREAD

**Issue by ItchyDitchy** [PlaceholderAPI/Javascript-Expansion#7]
### Title
>JavaScript Extension Files not loading.

### Issue
> The extension is not loading the files I want to see, for example : javascript_placeholders.yml, /papijsp does not work, and the javascript_placeholders folder does not also load on the placeholders folder.

### Expected behaviour
> Fix the problem since javascript extension is a major extension for the developers.

### Actual behaviour
> Fix the problem...

### How to reproduce
> Nothing, I just downloaded the extension, place it on the extensions folder then /papi reload

**Comment by aBo0oDyy** [comment]
Hey,
First of all, `/papijsp reload` doesn't always work so use `/papi reload` instead, and you have to register the placeholder in the `javascript_placeholders.yml` file, then reload papi and it will create the JS file automatically in `javascripts` folder and then you can add your JavaScript code there and use the placeholder like this `%javascript_NAME%`, `NAME` is the name of the placeholder you gave it to in `javascript_placeholders.yml`.

Check [the wiki](https://github.com/PlaceholderAPI/Javascript-Expansion/wiki) for more info and examples.

**Comment by aBo0oDyy** [comment]
Issued is closed due to no reply from the author in the last 17 days.
